create TABLE PRODUCTO (
        PRODUCTO_ID NUMBER,
        NOMBRE VARCHAR2(160) NOT NULL,
        PRECIO NUMERIC(10,2) NOT NULL,
        CANTIDAD NUMERIC(10,0) NOT NULL,
        ESTADO CHAR(1 BYTE) DEFAULT 1
        );


insert into PRODUCTO(PRODUCTO_ID, NOMBRE, PRECIO, CANTIDAD) values (1, 'PRODUCTO', 250, 10);
insert into PRODUCTO(PRODUCTO_ID, NOMBRE, PRECIO, CANTIDAD) values (2, 'PRODUCTO2', 150, 20);

commit;

select PRODUCTO_ID, NOMBRE, PRECIO, CANTIDAD, ESTADO from PRODUCTO;



update PRODUCTO set PRECIO = 300 where PRODUCTO_ID=2;